- name: configure hadoop namenode 
  hosts: datanode
  tasks:
  
  - name: copy hadoop and jdk-8 package
    copy:
      src: "{{ item }}"
      dest: /root/ 
    loop: "{{ packages_path }}"



  - name: install jdk-8
    yum: 
      name: "/root/jdk-8u171-linux-x64.rpm"
      state: present 
      disable_gpg_check: true



  - name: check whether hadoop is installed or not
    command: "rpm -q hadoop"
    register: hadoop_install
    ignore_errors: true
    changed_when: false   

  - name: install hadoop 
    command: "rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force"
    when: hadoop_install.rc != 0
 

  - name: install config hdfs .xml file
    template:  
      src: "{{ item }}"
      dest: "/etc/hadoop/"
    loop: "{{ config_files_path }}" 
    
  - name: format  the namenode {{ dir_path }}
    command: "hadoop namenode -format -nonInteractive" 
    ignore_errors: true
    changed_when: false
    when: node_type == "node"
        


  - name: check whether the {{ node_type}}node service is runnig or not 
    shell: "jps | grep Node"
    register: hadoop_svc
    changed_when: false
    ignore_errors: false 


  - name: start the hadoop {{ node_type }}node  service 
    command: "hadoop-daemon.sh start {{ node_type}}node"
    when: "'Node' not in hadoop_svc.stdout"

  - name: print the report 
    command: "hadoop dfsadmin -report"
    register: hadoop_dn_report
    changed_when: false 

  - debug:
      msg: "{{ hadoop_dn_report.stdout }}"
   
